app = "videditor-jobs-autoscaler"
primary_region = "ams"

[build]
image = "flyio/fly-autoscaler:0.3"

[env]
FAS_PROMETHEUS_ADDRESS = "https://api.fly.io/prometheus/videditor"
FAS_PROMETHEUS_METRIC_NAME = "jobs"
FAS_PROMETHEUS_QUERY = "sum(videditor_jobs_running_and_queued{app='videditor-app'})"
FAS_APP_NAME = "videditor-jobs"
FAS_STARTED_MACHINE_COUNT = "max(1, ceil(jobs / 3))"

[metrics]
port = 9090
path = "/metrics"
